blank_issues_enabled: false
contact_links:
  - name: Support Questions & Other
    url: https://www.zen-cart.com/forum
    about: 'If you have a question or need help using Zen Cart, use https://www.zen-cart.com/forum'
  - name: Documentation Site
    url: https://docs.zen-cart.com
    about: For Zen Cart documentation, consult the docs.zen-cart.com site.
  - name: Documentation issue
    url: https://github.com/zencart/documentation
    about: For documentation issues, open a pull request at the zencart/documentation repository
